library(htmltools)
library(webshot2)
library(glue)
library(jsonlite)
library(googledrive)
library(magick)
library(httr)
library(ggplot2)

# Helper function to encode images to Base64
encode_image_base64 <- function(image_path) {
  base64 <- base64_enc(readBin(image_path, "raw", file.info(image_path)$size))
  mime_type <- ifelse(grepl("\\.png$", image_path, ignore.case = TRUE), "image/png", "image/jpeg")
  paste0("data:", mime_type, ";base64,", base64)
}


generate_explorer_card <- function(output_file, 
                                   explorer_name, 
                                   explorer_score, 
                                   map_image, 
                                   bird_image, 
                                   bird_text, 
                                   region, 
                                   num_districts, 
                                   total_districts, 
                                   date, 
                                   photographer,
                                   template_file,
                                   cssfile,
                                   filetype = 'html') {
  
  # Convert Leaflet map to image
  temp_map_image <- tempfile(fileext = ".png")
  log_message("Generating map snapshot", 0)
  ggsave(temp_map_image, map_image)
  
  # Encode images to Base64
  map_base64 <- encode_image_base64(temp_map_image)
  bird_base64 <- encode_image_base64(bird_image)
  template_base64 <- encode_image_base64(template_file)
  
  # Generate the HTML structure
  temp_html <- tempfile(fileext = ".html")
  css_content <- readLines(cssfile, warn = FALSE)
  log_message(css_content, 4)
  
  
  html_content <- tags$html(
    tags$head(
      tags$style(HTML(paste(css_content, collapse = "\n")))
    ),    
    tags$body(
      tags$div(
        tags$img(src = template_base64, id = "template"),
        tags$div(id = "dynamic-content",
             # Explorer name and score
             tags$div(class = "explorer-name-text",
                      tags$p(class = "explorer-name-text", paste("EXPLORER:", explorer_name))
             ),
             tags$div(class = "explorer-score-text",
                      tags$p(class = "explorer-score-text", paste("EXPLORER SCORE:", explorer_score))
             ),
             #tags$div(id = "map-image", map_image),
             #tags$div(id = "map-image", tags$script(HTML(as.character(map_image)))),
             # Map image
             tags$img(src = map_base64, class = "map-image"),
             # Bird image and text
             tags$img(src = bird_base64, class = "bird-image"),
             tags$div(
               class = "bird-text",
               bird_text
             ),
             # Region and district numbers
#             tags$div(class = "region-text",
#                      tags$p(class = "region-text", paste("REGION:", region))
#             ),
#             tags$div(class = "district-text",
#                      tags$p(class = "district-text", paste0("NUMBER OF DISTRICTS: ", num_districts, " (", total_districts, ")"))
#             ),
             
             # Region and district numbers
             tags$div(class = "region-text",
                      tags$p(class = "region-text", HTML(paste0("<b>REGION:</b> ", region)))
             ),
             tags$div(class = "district-text",
                      tags$p(class = "district-text", HTML(paste0("<b>NUMBER OF DISTRICTS:</b> ", num_districts, " (", total_districts, ")")))
             ),
             # Date
             tags$div(class = "date-text",
                      tags$p(class = "date-text", paste("Generated by birdcountindia.shinyapps.io/Xplorerscore on:", date))
             ),
             tags$div(class = "photographer-text",
                      tags$p(class = "photographer-text", paste("©", photographer))
             )
        )
      )
    )
  )

  log_message (paste("Saving html",temp_html), 0)
  save_html(html_content, file = temp_html)
  
  if (filetype == 'jpg')
  {
    print("Grabbing screenshot")
    # Enable only in paid account
    tryCatch( {
    webshot2::webshot(
      temp_html,
      file = output_file,
      selector = "body",
      vwidth = 1088,
      vheight = 1366,
      zoom = 2,
      cliprect = c(8, 8, 1080, 1360),  # Define the exact area to capture, experimented and found out
      delay = as.integer(unlist(config_util$store[["chromateDelay"]]))
    )}, error = function (e) {
      log_message(paste("Card generation failed:", e$message, "\n"), 0)
      return (1)
    })
  }
  else
  {
    save_html(html_content, file = output_file)
  }
}

# Function to download and crop an image from Google Drive folder
download_and_crop_image <- function(file_id, width, height) {
  temp_cropped_path <- NULL

  # Construct the URL to download the file directly
  image_url <- paste0("https://drive.google.com/uc?export=download&id=", file_id)
  
  # Temporary file paths for the original and cropped images
  temp_image_path <- tempfile(fileext = ".png")
  temp_cropped_path <- tempfile(fileext = ".png")
  
  # Download the image
  download.file(image_url, temp_image_path, mode = "wb")
  
  # Read the image using magick
  image <- image_read(temp_image_path)
  
  # Crop the image (modify geometry as per your requirements)
  cropped_image <- image_scale(image, paste(width, "x", height))
  
  # Save the cropped image to the temporary file
  image_write(cropped_image, temp_cropped_path)
  # Return the path to the cropped image
  return(temp_cropped_path)
}

generate_random_with_seed <- function(name, maximum) {
  # Calculate seed based on the sum of utf8ToInt(name)
  seed <- sum(utf8ToInt(name))
  
  # Set the seed for random number generation
  set.seed(seed)
  
  # Generate a random number between 0, 1, and 2
  return(sample(0:maximum, 1))
}


getBirdPosterIndex <- function (posterTable, name, score, region)
{
  selected <- NULL
# Selecting the right index from the table  
  if (!is.null(posterTable) && nrow(posterTable) > 0) {
    # Selecting the right index from the table  
    if (region == "India")
    {
      selected <- posterTable %>% 
        filter ( (score < posterTable$UpperLimit) & (score >= posterTable$LowerLimit))
      maxindex <- 2 # Random numbers are 0, 1, 2
    }
    else
    {
      selected <- posterTable %>% 
                    arrange (UpperLimit) %>% 
                        slice(1:21) # No range selection for states, all species except the top three
      maxindex <- 20
    }

    index <- generate_random_with_seed (name, maxindex)
    selected <- selected %>% 
                  slice(index + 1) # Add 1 because R indexing starts at 1, not 0
    
  }
  return (selected)
}


testcard <- function()
{
  output_file = ".\\test\\explorercard.jpg"
  if (file.exists(output_file)) {
    file.remove(output_file)
    print("removed file")
  }
  
  state = "Odisha"
#  testdata <- read.csv(".\\test\\test.csv", sep=";")
  testdata <- read.csv(".\\test\\test.csv", sep = ";", dec = ",", stringsAsFactors = FALSE)
  shapefile_data <- st_read("ind_dist.shp")
  if (state != "India")
  {
    testdata <- testdata %>% filter (State == state)
    shapefile_data <- shapefile_data %>% filter (STATE == state)
  }
  
  legendPosition <- read.csv(".\\test\\StateLegend.csv") %>% 
                        filter (State == state) %>% 
                        select(LegendPosition) %>% 
                        pull()
    
  map_data <- prepareExploreMapData(testdata, shapefile_data)
  map <- createMap4Save(map_data, 
                        "ExplorerScore",
                        2.0,
                        "darkgray",
                        1.0,
                        legendPosition,
                        #                        ifelse ((state == "Odisha") | (state == "Assam"), "bottomright", ifelse (state == "Arunachal Pradesh", "topleft", "bottomleft")),
                        "Purples",
                        "white")

  png_file <- paste0("intermediateMap", state, ".png")
  ggsave(png_file, map)
  
  ## Example usage
  generate_explorer_card(
    output_file = output_file,
    explorer_name = "PRAVEEN J",
    explorer_score = 469,
    map_image = map, #".\\test\\map.png",                # Path to the map PNG file
    bird_image = ".\\test\\redmunia.png",       # Path to the bird PNG file
    bird_text = "You are like a Whiskered Tern, skimming gracefully across vast wetlands, ever in search of new birds, guided by curiosity and the open sky.",
    region = "INDIA",
    num_districts = 461,
    total_districts = 735,
    date = "09/08/2025",
    photographer = "Saswat Mishra",
  #  template_file = ".\\test\\Explorer Score (1088 x 1360 px).png",       # Path to the template PNG file,
    template_file = "template.png",       # Path to the template PNG file,
    cssfile = "bcicardstyle.css",
    filetype = 'jpg'
   )
}
#testcard()
